ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123'
  auth: 
    jwtSecret: 2d1d307f-73f7-43c2-8447-fb6911a500a9
    jwtExpirationTimeMs: 14400000
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost